### ISSUE TITLE
TODO before workshop

### ISSUE THREAD

**Issue by lucydot** [ASE-Workshop-2023/tutorial#2]
## Highest Priority

- [x] Write dynamics tutorial code (@ajjackson ?)
- [x] Format and expand dynamics tutorial ( @lucydot )
- [x] Update electronic structure tutorial (@pietrodelugas ?)
- [x] Sort out the Docker image so that calculations can be ran (see email) (joint effort needed here I think)
- [x] Sort out QE sockets example so more of an extension task

## High priority

- [ ] Draft example code answers to each of the exercises, and upload these to the site ( @lucydot )
- [x] Do a full run through on the Daresbury system (@prakayastha)
- [ ] Read through each chapter ( @ajjackson @pietrodelugas @lucydot  - if we read through chapters we have contributed to)
  - [x] @ajjackson 
  - [ ] @pietrodelugas 
  - [x] @lucydot
- [x] Update viewing instructions to use `view(atoms,viewer='ngl')` see [here](https://wiki.fysik.dtu.dk/ase/ase/visualize/visualize.html

## Can wait

- [x] Update images so that they reflect those generated using `view`.
- [ ] Write setup instructions for people who want to run calculations on their own system (@lucydot , will need help from others)
- [ ] Highlight that the MD example is an example of when things aren't correct!
- [ ] Highlight GAP potential as the SI of a research paper
- [x] Check and fix links to external websites throughout (didn't want to break writing flow by finding website, so there are lots of links missing) (@lucydot )
- [ ] Make some introductory slides covering chapter 1 (introduction) content (@lucydot )
- [ ] Make clear GPAW parallel example is written in an external file

**Comment by ajjackson** [comment]
Throwing down some notes here that could possibly be tidied into TODOs  or separate issues:

- The `-nk` parameter to Quantum Espresso is an example of a parameter being passed to the external code. This is distinct from the `-np` parameter which goes to `mpirun` (and is, I believe, actually unnecessary...)
- It would be worth saying something about that: it highlights that a Profile contains information about _how an executable is run_ (rather than what ASE does with the files etc.).
- There is another example of that where the MOPAC command is hacked to hide the STDOUT. This is a bit weird actually because at the command line I find the default command which pipes away STDERR works fine. Some kind of magic about being run in a subprocess? Maybe it's better to keep that one glossed over as it us currently.
- I did run into the OpenMP warning from Quippy, but then restarting the virtual image made that error go away. So it seems to be something a bit sporadic?
- Another issue with Quippy/GAP is that it crashes the kernel if an incorrect file path is provided. Not sure what we can do about that really... we _could_ provide some guard code that only instantiates the Calculator if the file exists, but it would be more tedious to type out.

**Comment by prakayastha** [comment]
Hi @lucydot - I'm putting down some general comments here but I am not sure about what proposed changes to make...

In episode 3, it seems like any input file that I read is not readable through the ASE version installed on the Daresbury computer. (code section 2 in episode 3) I have tried a different cif file from what was uploaded and a POSCAR. When I try to run the code on my local computer, it seems to work. So I am just flagging up that perhaps the version of ASE is causing an issue... This point is a high priority as the rest of the episode is dependent on this code. 

In episode 4, the solution to "distorted sphalerite" gives an error "'list' object has no attribute 'translate'". And for "water animation" I am able to view the C60 but unable to see the moving atoms as a gif. I have a feeling this is again an issue of the ASE version installed because it works just fine on my local computer. 

In episode 7, I am unable to import quippy.potential. I have to install quippy to pip install that is suggested in the Note above code patch 2, but I am unsuccessful in doing. As you had suggested in our previous discussion @lucydot - that the training environment should have this preinstalled, I would highly suggest if someone crosschecked this particular point. 

In episode 8, pesudo_dir is not defined at line 376. This should be defined similarly to how it is in episode 9 such as "pseudo_dir = Path.home() / 'SSSP-1.2.1_PBE_efficiency'"

In episode 11, again quippy does not work for me so I am not able to test anything beyond line 247.

**Comment by lucydot** [comment]
Thanks @prakayastha, will take a look at these issues tomo. @ajjackson @pietrodelugas just at-ing you so you are kept int he loop.

**Comment by lucydot** [comment]
Hi @prakayastha thanks for catching these errors, v. useful!

> In episode 3, it seems like any input file that I read is not readable through the ASE version installed on the Daresbury computer. 

Problem fixed; the `wget` file was incorrect, so that the .cif file was actually html.

> In episode 4, the solution to "distorted sphalerite" gives an error "'list' object has no attribute 'translate'". 

Fixed! A line of code must have got lost in translation....

> In episode 7, I am unable to import quippy.potential

I think this error may be related to filepaths, as if Quippy can't find potential filepath it throws a very unuseful error (as adam comments above). Now specifying a directory to unzip the potentials into, so others shouldn't face similar problem.

> In episode 8, pesudo_dir is not defined at line 376. This should be defined similarly to how it is in episode 9 such as "pseudo_dir = Path.home() / 'SSSP-1.2.1_PBE_efficiency'"

Fixed!

**Comment by lucydot** [comment]
@ajjackson @pietrodelugas  - getting an error running the QE code with mpi: `CalledProcessError: Command '['mpirun', 'pw.x', '-in', 'espresso.pwi']' returned non-zero exit status 1.`

For the first QE example

from calculations_in_parallel tutorial:
```
atoms = ase.build.bulk('Si')
atoms.calc = calc
atoms.get_potential_energy()
```

I guess we can discuss tomorrow; think it may not be finding the `pw.x` perhaps?
QE example in following tutorial running fine so I think it is something not too difficult to solve.

**Comment by lucydot** [comment]
additional note here that I have swapped properties and dynamics slots in the online timetable to reflect the order we approach in the tutorial.
